// © 2026 aiaiaiai · aiaiaiai.org
// SPDX-License-Identifier: MPL-2.0

export {
  AVATAR_BODY_REGIONS,
  AVATAR_CATALOG,
  AVATAR_CATALOG_MATCHES_IDENTITY,
  AVATAR_SLOTS,
  DASHA_2_RIG_VERSION,
  REGISTERED_AVATAR_MODELS,
  WARDROBE_ITEMS,
  avatarModelDefinition,
  clearAvatarSlot,
  editableSlots,
  equipWardrobeItem,
  equippedIn,
  equippedWardrobe,
  hiddenBodyRegions,
  isAvatarModelEditable,
  isPublishedAvatarModel,
  parseAvatarAppearance,
  resolveAvatarAppearance,
  resolveAvatarSelection,
  serializeAvatarAppearance,
  supportsAvatarModel,
  validateAvatarAppearance,
  wardrobeItem,
  wardrobeItemsFor,
  type AvatarAppearance,
  type AvatarAppearanceCapability,
  type AvatarAppearanceRejection,
  type AvatarAppearanceSchema,
  type AvatarAppearanceValidation,
  type AvatarBodyRegion,
  type AvatarModelDefinition,
  type AvatarSelection,
  type AvatarSlot,
  type AvatarSlotCardinality,
  type AvatarSlotSchema,
  type WardrobeChange,
  type WardrobeItem,
} from "./avatar-appearance";
export {
  AVATAR_IDENTITY_NODES,
  AVATAR_IDENTITY_REGIONS,
  AVATAR_NODE_SEPARATOR,
  avatarBodyRegionNode,
  avatarWardrobeNode,
  resolveAvatarScene,
  resolveSelectedAvatarScene,
  sceneDrawsNode,
  type ResolvedAvatarScene,
} from "./avatar-scene";
export {
  createAvaiaMovementController,
  type AvaiaMovementController,
  type AvaiaMovementControllerOptions,
  type MovementState,
  type WorldPosition,
} from "./avaia-movement-controller";
export {
  hasAvaiaProfileAccess,
  PublishAvaiaLocation,
  ReadAvaiaProfile,
  UpdateAvaiaProfile,
  type AvaiaConfigurationState,
  type AvaiaLocationProjection,
  type AvaiaLocationPublishRejection,
  type AvaiaLocationPublishResult,
  type AvaiaProfileAccessPort,
  type AvaiaProfileProjection,
  type AvaiaProfileReadResult,
  type AvaiaProfileUpdateRejection,
  type AvaiaProfileUpdateResult,
} from "./avaia-profile";
export {
  hasPubInfoAccess,
  type ExperienceEarner,
  type ExperienceEvent,
  type ExperiencePublication,
  type PubInfoAccessPort,
  type PubInfoExperience,
  type PubInfoExperienceResult,
  type PubInfoRejection,
} from "./pub-info";
export {
  removeBondLocationOverride,
  resolveBondLocationPresentation,
  setBondLocationOverride,
  type BondLocationOverrides,
  type BondLocationPresentation,
  type BondLocationPresentationSource,
} from "./bond-location-presentation";
export {
  BOND_PROVIDER_TYPES,
  bondProviderConnection,
  bondProviderOpenTarget,
  bondProviderOpenTargets,
  connectBondProvider,
  connectedBondProviders,
  disconnectBondProvider,
  isBondProviderConnected,
  isBondProviderType,
  type BondProviderAccount,
  type BondProviderAttachment,
  type BondProviderConnections,
  type BondProviderDetachment,
  type BondProviderOpenKind,
  type BondProviderOpenOptions,
  type BondProviderOpenTarget,
  type BondProviderType,
} from "./bond-providers";
export {
  createFailureNotice,
  type FailureKind,
  type FailureNotice,
  type FailureNoticeAction,
  type FailureNoticeCopy,
  type FailureNoticeTone,
  type FailureReport,
} from "./failure-notice";
export {
  ReadRuntimeReadiness,
  type CorePubDressLabelErrorCode,
  type CorePubDressLabelResult,
  type CoreRuntimePort,
  type CoreRuntimeStatus,
  type CoreUnavailableReason,
  type RuntimeReadiness,
} from "./core-runtime";
export {
  AcknowledgeRecoveryKey,
  AuthenticateNativeIdentity,
  BeginBrowserProviderAuthorization,
  DisconnectBrowserProvider,
  DisconnectSelfProvider,
  ForgetRememberedBond,
  LinkBrowserProvider,
  LinkTelegramProvider,
  LogoutNativeIdentity,
  ReadBrowserProviderConnections,
  ReadBrowserProviderContext,
  ReadNativeIdentityContext,
  ReadProviderIdentity,
  RegisterNativeIdentity,
  RegisterProviderIdentity,
  AVATAR_MODELS,
  ChooseAvatarModel,
  RenameAvaiaSlug,
  isAvatarModel,
  type AvatarModel,
  type AvatarModelResult,
  type PublishedAvatarModel,
  type StoredAvatarModel,
  RenamePubDressSlug,
  SetProviderPassword,
  ResolvePubDress,
  ResolvePubDressLabel,
  formatPubDress,
  parsePubDress,
  type BrowserIdentityProvider,
  type BrowserProviderAvailability,
  type BrowserProviderConnectionsResult,
  type BrowserProviderContextResult,
  type BrowserProviderDisconnectResult,
  type BrowserProviderLinkResult,
  type IdentityAccessPort,
  type TelegramProviderLinkResult,
  type IdentityProjection,
  type NativeAuthenticationResult,
  type NativeIdentityContextResult,
  type NativeMutationResult,
  type NativeRecoveryResult,
  type NativeRegistrationResult,
  type ProviderIdentityLookupResult,
  type ProviderPasswordHost,
  type ProviderPasswordResult,
  type ProviderRegistrationResult,
  type ProviderSelfDisconnectResult,
  type PubDressLabelResolutionResult,
  type PubDressRenameResult,
  type PubDressSelection,
  type PubDressResolutionResult,
} from "./identity-registration";
export {
  PUB_DRESS_LABEL_MAX_LENGTH,
  PUB_DRESS_URL_SUFFIX_MAX_LENGTH,
  PUB_DRESS_URL_ZONE,
  formatPubDressUrl,
  normalizePubDressUrlSuffix,
  projectCorePubDressLabel,
  projectCorePubDressLabelComposition,
  suggestPubDressUrlSuffix,
  type PubDressLabelComposition,
  type PubDressLabelDerivation,
  type PubDressLabelRejection,
  type PubDressLabelStem,
} from "./pub-dress-url";
